language: node_js
node_js:
- node
dist: trusty
sudo: true
if: tag IS present
cache:
   directories:
     - node_modules
before_install:
  - sudo dpkg --add-architecture i386
  - wget -nc https://dl.winehq.org/wine-builds/Release.key
  - sudo apt-key add Release.key
  - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
  - sudo apt-get update
install:
  - npm install electron-packager --save-dev
  - npm install
  - sudo apt-get install --install-recommends winehq-stable
script:
  - npm run build:win-x64
  - npm run build:linux-x64
before_deploy:
  - git config --local user.name "tncga"
  - git config --local user.email "qokberk_akdeniz@hotmail.com"
  - cd release-builds/
  - zip -9 -r whats-up-darkness-win32-x64.zip whats-up-darkness-win32-x64/*
  - env GZIP=-9 tar cvzf whats-up-darkness-linux-x64.tar.gz whats-up-darkness-linux-x64
  - ls
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    - "release-builds/whats-up-darkness-win32-x64.zip"
    - "release-builds/whats-up-darkness-linux-x64.tar.gz"
  skip_cleanup: true
  overwrite: true
  on:
    repo: tncga/whats-up-darkness
    tags: true
