language: node_js
node_js:
- node
dist: trusty
sudo: true
if: tag IS present
cache:
   directories:
     - node_modules
before_install:
  - sudo dpkg --add-architecture i386
  - wget -nc https://dl.winehq.org/wine-builds/winehq.key
  - sudo apt-key add winehq.key
  - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ trusty main'
  - sudo apt update
install:
  - npm install electron-packager --save-dev
  - npm install electron-builder --save-dev
  - sudo apt install --install-recommends winehq-stable
script:
  - npm run build:win-x64
  - npm run build:linux-x64
  - npm run build:deb
before_deploy:
  - git config --local user.name $NAME
  - git config --local user.email $EMAIL
  - cd release-builds/
  - zip -9 -r whats-up-darkness-$TRAVIS_TAG-win32-x64.zip whats-up-darkness-win32-x64/*
  - env GZIP=-9 tar cvzf whats-up-darkness-$TRAVIS_TAG-linux-x64.tar.gz whats-up-darkness-linux-x64
  - ls
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    - "whats-up-darkness-$TRAVIS_TAG-win32-x64.zip"
    - "whats-up-darkness-$TRAVIS_TAG-linux-x64.tar.gz"
  skip_cleanup: true
  overwrite: true
  on:
    repo: tncga/whats-up-darkness
    tags: true
