language: node_js
node_js:
- node
dist: trusty
sudo: true
cache:
   directories:
     - node_modules

before_install:
  - sudo dpkg --add-architecture i386
  - wget -nc https://dl.winehq.org/wine-builds/Release.key
  - sudo apt-key add Release.key
  - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
  - sudo apt-get update
install:
  - npm install electron-packager --save-dev
  - npm install
  - sudo apt-get install --install-recommends winehq-stable
script:
  - npm run build:win-x64
before_deploy:
  - zip -r release-builds/whats-up-darkness-win32-x64 . -i release-builds/whats-up-darkness-win32-x64.zip
  - git config --local user.name "tncga"
  - git config --local user.email "qokberk_akdeniz@hotmail.com"
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "release-builds/release-builds/whats-up-darkness-win32-x64.zip"
  skip_cleanup: true
  overwrite: true
  on:
    repo: tncga/whats-up-darkness
    tags: true
